const mockFlowData = {
  nodes: [
    {
      type: 'node',
      size: '30*30',
      shape: 'flow-circle',
      color: '#32CD32',
      NodeType: 'OBJECT',
      x: 566.34375,
      y: 137.5,
      id: 'u61zyq9cxzm',
      parent: 'iqmgpcqfgok',
      FlowIndex: 4,
      systemCreate: true,
      xattrs: {
        FuntionObjSourceType: 'CreateNew',
        PreviousNode: '',
      },
      index: 2,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'url',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 351.34375,
      y: 202.5,
      id: '0psprz1vqeri',
      parent: 'iqmgpcqfgok',
      FlowIndex: 4,
      ParamIndex: 1,
      systemCreate: true,
      xattrs: {
        name: 'url',
        type: 'String',
        direction: 'In',
        SourceType: 'ProcessPara',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'url全局',
          DataType: 'STRING',
          Direction: 'IN',
          DefaultValue: '无',
        },
        PreviousNode: '',
      },
      index: 3,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'return',
      color: '#32CD32',
      NodeType: 'OUTPUT',
      x: 641.34375,
      y: 202.5,
      id: 'k7oyk8c8phf',
      parent: 'iqmgpcqfgok',
      FlowIndex: 4,
      OutParamIndex: 2,
      systemCreate: true,
      xattrs: {
        direction: 'Out',
        name: 'return',
        type: 'long',
        SourceType: 'Constant',
        DataSource: '',
      },
      index: 4,
    },
    {
      type: 'node',
      size: '30*30',
      shape: 'flow-circle',
      color: '#32CD32',
      NodeType: 'OBJECT',
      x: 632.84375,
      y: 622,
      id: 'nwl5nfuwre',
      parent: '2evplonm4p7',
      FlowIndex: 2,
      systemCreate: true,
      xattrs: {
        FuntionObjSourceType: 'PreviousCallReturnObject',
        PreviousNode: 3,
      },
      index: 9,
    },
    {
      type: 'node',
      size: '30*30',
      shape: 'flow-circle',
      color: '#32CD32',
      NodeType: 'OBJECT',
      x: 591.34375,
      y: 345,
      id: 'p4jkd7swgy',
      parent: '1pia2d780hf',
      FlowIndex: 3,
      systemCreate: true,
      xattrs: {
        FuntionObjSourceType: 'PreviousCallCreateObject',
        PreviousNode: 4,
      },
      index: 10,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'height',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 376.34375,
      y: 360,
      id: '6hrk7qeujic',
      parent: '1pia2d780hf',
      FlowIndex: 3,
      ParamIndex: 1,
      systemCreate: true,
      xattrs: {
        name: 'height',
        type: 'double',
        direction: 'In',
        SourceType: 'ProcessPara',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'height全局',
          DataType: 'FLOAT',
          Direction: 'IN',
          DefaultValue: '555',
        },
        PreviousNode: '',
      },
      index: 11,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'offset',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 376.34375,
      y: 410,
      id: 't65jazitlc8',
      parent: '1pia2d780hf',
      FlowIndex: 3,
      ParamIndex: 2,
      systemCreate: true,
      xattrs: {
        name: 'offset',
        type: 'double',
        direction: 'In',
        SourceType: 'PreviousCallReturnValue',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'offset',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: 4,
      },
      index: 12,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'pnt',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 376.34375,
      y: 460,
      id: '7o5c80aj11x',
      parent: '1pia2d780hf',
      FlowIndex: 3,
      ParamIndex: 3,
      systemCreate: true,
      xattrs: {
        name: 'pnt',
        type: 'Dot',
        direction: 'In',
        SourceType: 'FLSNULL',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'pnt',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: '',
      },
      index: 13,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'return',
      color: '#32CD32',
      NodeType: 'OUTPUT',
      x: 666.34375,
      y: 410,
      id: 'rdkp37kw93j',
      parent: '1pia2d780hf',
      FlowIndex: 3,
      OutParamIndex: 4,
      systemCreate: true,
      xattrs: {
        direction: 'Out',
        name: 'return',
        type: 'ViewPnt',
        SourceType: 'Constant',
        DataSource: '',
      },
      index: 14,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'xCellSize',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 417.84375,
      y: 612,
      id: 'bflj0z03fg',
      parent: '2evplonm4p7',
      FlowIndex: 2,
      ParamIndex: 1,
      systemCreate: true,
      xattrs: {
        name: 'xCellSize',
        type: 'double',
        direction: 'In',
        SourceType: 'ProcessPara',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'xCellSize全局',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '55',
        },
        PreviousNode: '',
      },
      index: 20,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'yCellSize',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 417.84375,
      y: 662,
      id: 'geegpso7wz6',
      parent: '2evplonm4p7',
      FlowIndex: 2,
      ParamIndex: 2,
      systemCreate: true,
      xattrs: {
        name: 'yCellSize',
        type: 'double',
        direction: 'In',
        SourceType: 'Constant',
        DataSource: '55.5',
        ProcessParaInfo: {
          Name: 'yCellSize',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: '',
      },
      index: 21,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'xMin',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 417.84375,
      y: 712,
      id: '9ada8k7yu9w',
      parent: '2evplonm4p7',
      FlowIndex: 2,
      ParamIndex: 3,
      systemCreate: true,
      xattrs: {
        name: 'xMin',
        type: 'double',
        direction: 'In',
        SourceType: 'PreviousCallInputParamater',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'xMin',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: '3-2',
      },
      index: 22,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'yMin',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 417.84375,
      y: 762,
      id: 'hvuy071a284',
      parent: '2evplonm4p7',
      FlowIndex: 2,
      ParamIndex: 4,
      systemCreate: true,
      xattrs: {
        name: 'yMin',
        type: 'double',
        direction: 'In',
        SourceType: 'PreviousObject',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'yMin',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: 3,
      },
      index: 23,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'return',
      color: '#32CD32',
      NodeType: 'OUTPUT',
      x: 707.84375,
      y: 687,
      id: 'e5a43m9qzr',
      parent: '2evplonm4p7',
      FlowIndex: 2,
      OutParamIndex: 5,
      systemCreate: true,
      xattrs: {
        direction: 'Out',
        name: 'return',
        type: 'ShiftInfo',
        SourceType: 'Constant',
        DataSource: '',
      },
      index: 24,
    },
    {
      type: 'node',
      size: '100*40',
      shape: 'flow-capsule',
      label: 'ShiftInfo',
      color: '#FF9010',
      NodeType: 'METHOD',
      paramsList: [
        {
          name: 'xCellSize',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'yCellSize',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'xMin',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'yMin',
          type: 'double',
          direction: 'In',
        },
        {
          direction: 'Out',
          name: 'return',
          type: 'ShiftInfo',
        },
      ],
      xattrs: {
        functionId: '0431520E21E6E3043E5E8C8C2DDE05E5',
        functionName: 'ShiftInfo',
        returnValueType: 'ShiftInfo',
        parameters: [
          {
            name: 'xCellSize',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'yCellSize',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'xMin',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'yMin',
            type: 'double',
            direction: 'In',
          },
          {
            direction: 'Out',
            name: 'return',
            type: 'ShiftInfo',
          },
        ],
        key: '0431520E21E6E3043E5E8C8C2DDE05E5',
        libName: 'MapGIS',
        jarName: 'mapgis_geoanalyst.jar',
        className: 'com.zondy.mapgis.analyst.analystraster.ShiftInfo',
        isLeaf: true,
        switcherIcon: {
          type: {},
          key: null,
          ref: null,
          props: {
            'data-inspector-line': '735',
            'data-inspector-column': '34',
            'data-inspector-relative-path':
              'src\\pages\\EditorFlow\\components\\EditorItemPanel\\FlowItemPanel.tsx',
          },
          _owner: null,
          _store: {},
        },
        PreviousNode: '',
      },
      x: 567.84375,
      y: 687,
      id: '595dde23',
      index: 31,
      FlowIndex: 2,
      parent: '2evplonm4p7',
    },
    {
      type: 'node',
      size: '100*40',
      shape: 'flow-capsule',
      label: 'ViewPnt',
      color: '#FF9010',
      NodeType: 'METHOD',
      paramsList: [
        {
          name: 'height',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'offset',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'pnt',
          type: 'Dot',
          direction: 'In',
        },
        {
          direction: 'Out',
          name: 'return',
          type: 'ViewPnt',
        },
      ],
      xattrs: {
        functionId: '560955475BF741D6C3BCCA3B23048E0D',
        functionName: 'ViewPnt',
        returnValueType: 'ViewPnt',
        parameters: [
          {
            name: 'height',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'offset',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'pnt',
            type: 'Dot',
            direction: 'In',
          },
          {
            direction: 'Out',
            name: 'return',
            type: 'ViewPnt',
          },
        ],
        key: '560955475BF741D6C3BCCA3B23048E0D',
        libName: 'MapGIS',
        jarName: 'mapgis_geoanalyst.jar',
        className: 'com.zondy.mapgis.analyst.analystraster.ViewPnt',
        isLeaf: true,
        switcherIcon: {
          type: {},
          key: null,
          ref: null,
          props: {
            'data-inspector-line': '735',
            'data-inspector-column': '34',
            'data-inspector-relative-path':
              'src\\pages\\EditorFlow\\components\\EditorItemPanel\\FlowItemPanel.tsx',
          },
          _owner: null,
          _store: {},
        },
        PreviousNode: '',
      },
      x: 526.34375,
      y: 410,
      id: '1ed3aaa6',
      index: 32,
      FlowIndex: 3,
      parent: '1pia2d780hf',
    },
    {
      type: 'node',
      size: '100*40',
      shape: 'flow-capsule',
      label: 'openByURL',
      color: '#FF9010',
      NodeType: 'METHOD',
      paramsList: [
        {
          name: 'url',
          type: 'String',
          direction: 'In',
        },
        {
          direction: 'Out',
          name: 'return',
          type: 'long',
        },
      ],
      xattrs: {
        functionId: '034331D204A0C54C2C52B5A97C35D88F',
        functionName: 'openByURL',
        returnValueType: 'long',
        parameters: [
          {
            name: 'url',
            type: 'String',
            direction: 'In',
          },
          {
            direction: 'Out',
            name: 'return',
            type: 'long',
          },
        ],
        key: '034331D204A0C54C2C52B5A97C35D88F',
        libName: 'MapGIS',
        jarName: 'mapgis_geoclass.jar',
        className: 'com.zondy.mapgis.geodatabase.SFeatureCls',
        isLeaf: true,
        switcherIcon: {
          type: {},
          key: null,
          ref: null,
          props: {
            'data-inspector-line': '735',
            'data-inspector-column': '34',
            'data-inspector-relative-path':
              'src\\pages\\EditorFlow\\components\\EditorItemPanel\\FlowItemPanel.tsx',
          },
          _owner: null,
          _store: {},
        },
        PreviousNode: '',
      },
      x: 501.34375,
      y: 202.5,
      id: 'f879c506',
      index: 33,
      FlowIndex: 4,
      parent: 'iqmgpcqfgok',
    },
    {
      type: 'node',
      size: '60*60',
      shape: 'flow-circle',
      label: '开始节点',
      color: '#0573E9',
      NodeType: 'START',
      paramsList: [],
      x: 496.34375,
      y: -10,
      id: '747ae4e0',
      index: 34,
      FlowIndex: 1,
    },
    {
      type: 'node',
      size: '60*60',
      shape: 'flow-circle',
      label: '结束节点',
      color: '#0573E9',
      NodeType: 'END',
      paramsList: [],
      x: 549.015625,
      y: 878,
      id: '3783ae14',
      index: 35,
      FlowIndex: 5,
    },
  ],
  edges: [
    {
      source: 'f879c506',
      sourceAnchor: 1,
      target: 'u61zyq9cxzm',
      targetAnchor: 2,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 4,
      id: 'd9c9f157',
      index: 6,
    },
    {
      source: '0psprz1vqeri',
      sourceAnchor: 1,
      target: 'f879c506',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 4,
      id: 'ba48aa66',
      index: 7,
    },
    {
      source: 'f879c506',
      sourceAnchor: 1,
      target: 'k7oyk8c8phf',
      targetAnchor: 3,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 4,
      id: 'a38a3560',
      index: 8,
    },
    {
      source: '1ed3aaa6',
      sourceAnchor: 1,
      target: 'p4jkd7swgy',
      targetAnchor: 2,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 3,
      id: 'ce6a0acc',
      index: 15,
    },
    {
      source: '6hrk7qeujic',
      sourceAnchor: 1,
      target: '1ed3aaa6',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 3,
      id: 'd78c43a9',
      index: 16,
    },
    {
      source: 't65jazitlc8',
      sourceAnchor: 1,
      target: '1ed3aaa6',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 3,
      id: '2337c7f1',
      index: 17,
    },
    {
      source: '7o5c80aj11x',
      sourceAnchor: 1,
      target: '1ed3aaa6',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 3,
      id: '495f49de',
      index: 18,
    },
    {
      source: '1ed3aaa6',
      sourceAnchor: 1,
      target: 'rdkp37kw93j',
      targetAnchor: 3,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 3,
      id: '728fbd87',
      index: 19,
    },
    {
      source: '595dde23',
      sourceAnchor: 1,
      target: 'nwl5nfuwre',
      targetAnchor: 2,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 2,
      id: 'cb4a171c',
      index: 25,
    },
    {
      source: 'bflj0z03fg',
      sourceAnchor: 1,
      target: '595dde23',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 2,
      id: '41d1126f',
      index: 26,
    },
    {
      source: 'geegpso7wz6',
      sourceAnchor: 1,
      target: '595dde23',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 2,
      id: '8a0e3db4',
      index: 27,
    },
    {
      source: '9ada8k7yu9w',
      sourceAnchor: 1,
      target: '595dde23',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 2,
      id: '16b6e5bd',
      index: 28,
    },
    {
      source: 'hvuy071a284',
      sourceAnchor: 1,
      target: '595dde23',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 2,
      id: 'a8c1b251',
      index: 29,
    },
    {
      source: '595dde23',
      sourceAnchor: 1,
      target: 'e5a43m9qzr',
      targetAnchor: 3,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 2,
      id: '4080ac8e',
      index: 30,
    },
    {
      source: 'u61zyq9cxzm',
      sourceAnchor: 1,
      target: 'p4jkd7swgy',
      targetAnchor: 0,
      id: 'dd25fdbe',
      index: 36,
    },
    {
      source: 'rdkp37kw93j',
      sourceAnchor: 1,
      target: 'nwl5nfuwre',
      targetAnchor: 0,
      id: '7aeb0c3b',
      index: 37,
    },
    {
      source: 'k7oyk8c8phf',
      sourceAnchor: 1,
      target: 't65jazitlc8',
      targetAnchor: 3,
      id: '8ca461b0',
      index: 38,
    },
    {
      source: 't65jazitlc8',
      sourceAnchor: 3,
      target: '9ada8k7yu9w',
      targetAnchor: 3,
      id: '79b452d6',
      index: 39,
    },
    {
      source: 'p4jkd7swgy',
      sourceAnchor: 1,
      target: 'hvuy071a284',
      targetAnchor: 3,
      id: '5a663223',
      index: 40,
    },
    {
      source: '747ae4e0',
      sourceAnchor: 2,
      target: 'f879c506',
      targetAnchor: 0,
      id: '275452fd',
      From: 1,
      To: 4,
      index: 41,
    },
    {
      source: 'f879c506',
      sourceAnchor: 2,
      target: '1ed3aaa6',
      targetAnchor: 0,
      id: 'a423056c',
      From: 4,
      To: 3,
      index: 42,
    },
    {
      source: '1ed3aaa6',
      sourceAnchor: 2,
      target: '595dde23',
      targetAnchor: 0,
      id: 'f6a15d8b',
      From: 3,
      To: 2,
      index: 43,
    },
    {
      source: '595dde23',
      sourceAnchor: 2,
      target: '3783ae14',
      targetAnchor: 0,
      id: '84f086b2',
      From: 2,
      To: 5,
      index: 44,
    },
  ],
  groups: [
    {
      id: '2evplonm4p7',
      label: '改名',
      collapsed: false,
      FlowIndex: 2,
      x: 367.34375,
      y: 596.5,
      index: 0,
    },
    {
      id: 'iqmgpcqfgok',
      label: '通过url打开',
      collapsed: false,
      FlowIndex: 4,
      x: 300.84375,
      y: 122,
      index: 1,
    },
    {
      id: '1pia2d780hf',
      label: 'ViewPnt',
      collapsed: false,
      FlowIndex: 3,
      x: 325.84375,
      y: 329.5,
      index: 5,
    },
  ],
};

export default mockFlowData;
