const mockFlowData = {
  nodes: [
    {
      type: 'node',
      size: '60*60',
      shape: 'flow-circle',
      label: '开始节点',
      color: '#0573E9',
      NodeType: 'START',
      paramsList: [],
      x: 550.671875,
      y: -271.5,
      id: '80586e94',
      index: 0,
      FlowIndex: 1,
    },
    {
      type: 'node',
      size: '30*30',
      shape: 'flow-circle',
      color: '#EC3D3D',
      NodeType: 'OBJECT',
      x: 630.015625,
      y: 334.5,
      id: '0wsqltn3b1dj',
      parent: '4c84k0uphrb',
      FlowIndex: 4,
      systemCreate: true,
      xattrs: {
        FuntionObjSourceType: 'PreviousCallReturnObject',
        PreviousNode: 3,
      },
      index: 3,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'xCellSize',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 415.015625,
      y: 324.5,
      id: 'x4f7l5u7srg',
      parent: '4c84k0uphrb',
      FlowIndex: 4,
      ParamIndex: 1,
      systemCreate: true,
      xattrs: {
        name: 'xCellSize',
        type: 'double',
        direction: 'In',
        SourceType: 'ProcessPara',
        DataSource: 1,
        ProcessParaInfo: {
          Name: 'xCellSize全局3',
          DataType: 'STRING',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: '',
      },
      index: 4,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'yCellSize',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 415.015625,
      y: 374.5,
      id: '8xmghohp6v6',
      parent: '4c84k0uphrb',
      FlowIndex: 4,
      ParamIndex: 2,
      systemCreate: true,
      xattrs: {
        name: 'yCellSize',
        type: 'double',
        direction: 'In',
        SourceType: 'Constant',
        DataSource: '123.4',
        ProcessParaInfo: {
          Name: 'yCellSize',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: '',
      },
      index: 5,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'xMin',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 415.015625,
      y: 424.5,
      id: 'mgbgefez5bd',
      parent: '4c84k0uphrb',
      FlowIndex: 4,
      ParamIndex: 3,
      systemCreate: true,
      xattrs: {
        name: 'xMin',
        type: 'double',
        direction: 'In',
        SourceType: 'PreviousObject',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'xMin',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: 3,
      },
      index: 6,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'yMin',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 415.015625,
      y: 474.5,
      id: 'admy50eir2r',
      parent: '4c84k0uphrb',
      FlowIndex: 4,
      ParamIndex: 4,
      systemCreate: true,
      xattrs: {
        name: 'yMin',
        type: 'double',
        direction: 'In',
        SourceType: 'PreviousCallInputParamater',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'yMin',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: '3-2',
      },
      index: 7,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'return',
      color: '#32CD32',
      NodeType: 'OUTPUT',
      x: 705.015625,
      y: 399.5,
      id: 'jc602xr5hwa',
      parent: '4c84k0uphrb',
      FlowIndex: 4,
      OutParamIndex: 5,
      systemCreate: true,
      xattrs: {
        direction: 'Out',
        name: 'return',
        type: 'ShiftInfo',
        SourceType: 'Constant',
        DataSource: '',
      },
      index: 8,
    },
    {
      type: 'node',
      size: '30*30',
      shape: 'flow-circle',
      color: '#EC3D3D',
      NodeType: 'OBJECT',
      x: 614.015625,
      y: -154.5,
      id: 'a2wluk67obh',
      parent: '4b87k8qkz58',
      FlowIndex: 2,
      systemCreate: true,
      xattrs: {
        FuntionObjSourceType: 'CreateNew',
        PreviousNode: '',
      },
      index: 16,
    },
    {
      type: 'node',
      size: '30*30',
      shape: 'flow-circle',
      color: '#EC3D3D',
      NodeType: 'OBJECT',
      x: 620.015625,
      y: 85.5,
      id: '29y4yu4tslj',
      parent: 'h4o2czioea6',
      FlowIndex: 3,
      systemCreate: true,
      xattrs: {
        FuntionObjSourceType: 'PreviousCallCreateObject',
        PreviousNode: 2,
      },
      index: 17,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'height',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 405.015625,
      y: 100.5,
      id: '0yxd51r449a',
      parent: 'h4o2czioea6',
      FlowIndex: 3,
      ParamIndex: 1,
      systemCreate: true,
      xattrs: {
        name: 'height',
        type: 'double',
        direction: 'In',
        SourceType: 'ProcessPara',
        DataSource: 2,
        ProcessParaInfo: {
          Name: 'height全局2',
          DataType: 'FLOAT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: '',
      },
      index: 18,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'offset',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 405.015625,
      y: 150.5,
      id: '4zwflvuesg',
      parent: 'h4o2czioea6',
      FlowIndex: 3,
      ParamIndex: 2,
      systemCreate: true,
      xattrs: {
        name: 'offset',
        type: 'double',
        direction: 'In',
        SourceType: 'PreviousCallReturnValue',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'offset',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: 2,
      },
      index: 19,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'pnt',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 405.015625,
      y: 200.5,
      id: '1xmazvr9mbw',
      parent: 'h4o2czioea6',
      FlowIndex: 3,
      ParamIndex: 3,
      systemCreate: true,
      xattrs: {
        name: 'pnt',
        type: 'Dot',
        direction: 'In',
        SourceType: 'FLSNULL',
        DataSource: '',
        ProcessParaInfo: {
          Name: 'pnt',
          DataType: 'INT',
          Direction: 'IN',
          DefaultValue: '',
        },
        PreviousNode: '',
      },
      index: 20,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'return',
      color: '#32CD32',
      NodeType: 'OUTPUT',
      x: 695.015625,
      y: 150.5,
      id: 'a0e02mt8bu',
      parent: 'h4o2czioea6',
      FlowIndex: 3,
      OutParamIndex: 4,
      systemCreate: true,
      xattrs: {
        direction: 'Out',
        name: 'return',
        type: 'ViewPnt',
        SourceType: 'Constant',
        DataSource: '',
      },
      index: 21,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'url',
      color: '#32CD32',
      NodeType: 'INPUT',
      x: 399.015625,
      y: -89.5,
      id: '587q0k3rpar',
      parent: '4b87k8qkz58',
      FlowIndex: 2,
      ParamIndex: 1,
      systemCreate: true,
      xattrs: {
        name: 'url',
        type: 'String',
        direction: 'In',
        SourceType: 'ProcessPara',
        DataSource: 3,
        ProcessParaInfo: {
          Name: 'url全局1',
          DataType: 'STRING',
          Direction: 'IN',
          DefaultValue: '无',
        },
        PreviousNode: '',
      },
      index: 27,
    },
    {
      type: 'node',
      size: '100*30',
      shape: 'flow-rect',
      label: 'return',
      color: '#32CD32',
      NodeType: 'OUTPUT',
      x: 689.015625,
      y: -89.5,
      id: 'g54ag8nvc95',
      parent: '4b87k8qkz58',
      FlowIndex: 2,
      OutParamIndex: 2,
      systemCreate: true,
      xattrs: {
        direction: 'Out',
        name: 'return',
        type: 'long',
        SourceType: 'Constant',
        DataSource: '',
      },
      index: 28,
    },
    {
      type: 'node',
      size: '100*40',
      shape: 'flow-capsule',
      label: 'openByURL',
      color: '#0573E9',
      NodeType: 'METHOD',
      paramsList: [
        {
          name: 'url',
          type: 'String',
          direction: 'In',
        },
        {
          direction: 'Out',
          name: 'return',
          type: 'long',
        },
      ],
      xattrs: {
        functionId: '034331D204A0C54C2C52B5A97C35D88F',
        functionName: 'openByURL',
        returnValueType: 'long',
        parameters: [
          {
            name: 'url',
            type: 'String',
            direction: 'In',
          },
          {
            direction: 'Out',
            name: 'return',
            type: 'long',
          },
        ],
        key: '034331D204A0C54C2C52B5A97C35D88F',
        libName: 'MapGIS',
        jarName: 'mapgis_geoclass.jar',
        className: 'com.zondy.mapgis.geodatabase.SFeatureCls',
        isLeaf: true,
        switcherIcon: {
          type: {},
          key: null,
          ref: null,
          props: {
            'data-inspector-line': '794',
            'data-inspector-column': '34',
            'data-inspector-relative-path':
              'src\\pages\\EditorFlow\\components\\EditorItemPanel\\FlowItemPanel.tsx',
          },
          _owner: null,
          _store: {},
        },
      },
      x: 549.015625,
      y: -89.5,
      id: '92ffe6eb',
      index: 32,
      FlowIndex: 2,
      parent: '4b87k8qkz58',
      systemCreate: true,
    },
    {
      type: 'node',
      size: '100*40',
      shape: 'flow-capsule',
      label: 'ViewPnt',
      color: '#0573E9',
      NodeType: 'METHOD',
      paramsList: [
        {
          name: 'height',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'offset',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'pnt',
          type: 'Dot',
          direction: 'In',
        },
        {
          direction: 'Out',
          name: 'return',
          type: 'ViewPnt',
        },
      ],
      xattrs: {
        functionId: '560955475BF741D6C3BCCA3B23048E0D',
        functionName: 'ViewPnt',
        returnValueType: 'ViewPnt',
        parameters: [
          {
            name: 'height',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'offset',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'pnt',
            type: 'Dot',
            direction: 'In',
          },
          {
            direction: 'Out',
            name: 'return',
            type: 'ViewPnt',
          },
        ],
        key: '560955475BF741D6C3BCCA3B23048E0D',
        libName: 'MapGIS',
        jarName: 'mapgis_geoanalyst.jar',
        className: 'com.zondy.mapgis.analyst.analystraster.ViewPnt',
        isLeaf: true,
        switcherIcon: {
          type: {},
          key: null,
          ref: null,
          props: {
            'data-inspector-line': '794',
            'data-inspector-column': '34',
            'data-inspector-relative-path':
              'src\\pages\\EditorFlow\\components\\EditorItemPanel\\FlowItemPanel.tsx',
          },
          _owner: null,
          _store: {},
        },
      },
      x: 555.015625,
      y: 150.5,
      id: 'ea0c3038',
      index: 33,
      FlowIndex: 3,
      parent: 'h4o2czioea6',
      systemCreate: true,
    },
    {
      type: 'node',
      size: '100*40',
      shape: 'flow-capsule',
      label: 'ShiftInfo',
      color: '#0573E9',
      NodeType: 'METHOD',
      paramsList: [
        {
          name: 'xCellSize',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'yCellSize',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'xMin',
          type: 'double',
          direction: 'In',
        },
        {
          name: 'yMin',
          type: 'double',
          direction: 'In',
        },
        {
          direction: 'Out',
          name: 'return',
          type: 'ShiftInfo',
        },
      ],
      xattrs: {
        functionId: '0431520E21E6E3043E5E8C8C2DDE05E5',
        functionName: 'ShiftInfo',
        returnValueType: 'ShiftInfo',
        parameters: [
          {
            name: 'xCellSize',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'yCellSize',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'xMin',
            type: 'double',
            direction: 'In',
          },
          {
            name: 'yMin',
            type: 'double',
            direction: 'In',
          },
          {
            direction: 'Out',
            name: 'return',
            type: 'ShiftInfo',
          },
        ],
        key: '0431520E21E6E3043E5E8C8C2DDE05E5',
        libName: 'MapGIS',
        jarName: 'mapgis_geoanalyst.jar',
        className: 'com.zondy.mapgis.analyst.analystraster.ShiftInfo',
        isLeaf: true,
        switcherIcon: {
          type: {},
          key: null,
          ref: null,
          props: {
            'data-inspector-line': '794',
            'data-inspector-column': '34',
            'data-inspector-relative-path':
              'src\\pages\\EditorFlow\\components\\EditorItemPanel\\FlowItemPanel.tsx',
          },
          _owner: null,
          _store: {},
        },
      },
      x: 565.015625,
      y: 399.5,
      id: 'd2e3afa4',
      index: 34,
      FlowIndex: 4,
      parent: '4c84k0uphrb',
      systemCreate: true,
    },
    {
      type: 'node',
      size: '60*60',
      shape: 'flow-circle',
      label: '结束节点',
      color: '#0573E9',
      NodeType: 'END',
      paramsList: [],
      x: 577.015625,
      y: 580.5,
      id: 'd20d2666',
      index: 35,
      FlowIndex: 5,
    },
  ],
  edges: [
    {
      source: 'd2e3afa4',
      sourceAnchor: 1,
      target: '0wsqltn3b1dj',
      targetAnchor: 2,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 4,
      id: '6d520f00',
      index: 10,
    },
    {
      source: 'x4f7l5u7srg',
      sourceAnchor: 1,
      target: 'd2e3afa4',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 4,
      id: '66681b73',
      index: 11,
    },
    {
      source: '8xmghohp6v6',
      sourceAnchor: 1,
      target: 'd2e3afa4',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 4,
      id: '74ced34b',
      index: 12,
    },
    {
      source: 'mgbgefez5bd',
      sourceAnchor: 1,
      target: 'd2e3afa4',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 4,
      id: '0cd39189',
      index: 13,
    },
    {
      source: 'admy50eir2r',
      sourceAnchor: 1,
      target: 'd2e3afa4',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 4,
      id: '7954d4fe',
      index: 14,
    },
    {
      source: 'd2e3afa4',
      sourceAnchor: 1,
      target: 'jc602xr5hwa',
      targetAnchor: 3,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 4,
      id: '09172410',
      index: 15,
    },
    {
      source: 'ea0c3038',
      sourceAnchor: 1,
      target: '29y4yu4tslj',
      targetAnchor: 2,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 3,
      id: 'ffea6fb4',
      index: 22,
    },
    {
      source: '0yxd51r449a',
      sourceAnchor: 1,
      target: 'ea0c3038',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 3,
      id: 'db117a66',
      index: 23,
    },
    {
      source: '4zwflvuesg',
      sourceAnchor: 1,
      target: 'ea0c3038',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 3,
      id: 'd276fe2c',
      index: 24,
    },
    {
      source: '1xmazvr9mbw',
      sourceAnchor: 1,
      target: 'ea0c3038',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 3,
      id: 'd78e488c',
      index: 25,
    },
    {
      source: 'ea0c3038',
      sourceAnchor: 1,
      target: 'a0e02mt8bu',
      targetAnchor: 3,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 3,
      id: 'ac8fded2',
      index: 26,
    },
    {
      source: '92ffe6eb',
      sourceAnchor: 1,
      target: 'a2wluk67obh',
      targetAnchor: 2,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 2,
      id: '15f31999',
      index: 29,
    },
    {
      source: '587q0k3rpar',
      sourceAnchor: 1,
      target: '92ffe6eb',
      targetAnchor: 3,
      shape: 'flow-polyline-round',
      systemCreate: true,
      FlowIndex: 2,
      id: '2569a941',
      index: 30,
    },
    {
      source: '92ffe6eb',
      sourceAnchor: 1,
      target: 'g54ag8nvc95',
      targetAnchor: 3,
      systemCreate: true,
      shape: 'flow-smooth',
      FlowIndex: 2,
      id: '17bf9463',
      index: 31,
    },
    {
      source: '80586e94',
      sourceAnchor: 2,
      target: '92ffe6eb',
      targetAnchor: 0,
      id: '5ab8a718',
      From: 1,
      To: 2,
      color: '#0573E9',
      index: 36,
    },
    {
      source: '92ffe6eb',
      sourceAnchor: 2,
      target: 'ea0c3038',
      targetAnchor: 0,
      id: '04c65a71',
      From: 2,
      To: 3,
      color: '#0573E9',
      index: 37,
    },
    {
      source: 'ea0c3038',
      sourceAnchor: 2,
      target: 'd2e3afa4',
      targetAnchor: 0,
      id: 'd324f809',
      From: 3,
      To: 4,
      color: '#0573E9',
      index: 38,
    },
    {
      source: 'd2e3afa4',
      sourceAnchor: 2,
      target: 'd20d2666',
      targetAnchor: 0,
      id: '02562d57',
      From: 4,
      To: 5,
      color: '#0573E9',
      index: 39,
    },
    {
      source: 'g54ag8nvc95',
      sourceAnchor: 2,
      target: '4zwflvuesg',
      targetAnchor: 3,
      id: '5e416118',
      color: '#32CD32',
      index: 40,
    },
    {
      source: 'a2wluk67obh',
      sourceAnchor: 1,
      target: '29y4yu4tslj',
      targetAnchor: 0,
      id: '9f88a85e',
      color: '#EC3D3D',
      index: 41,
    },
    {
      source: '29y4yu4tslj',
      sourceAnchor: 3,
      target: 'mgbgefez5bd',
      targetAnchor: 3,
      id: '88acd39e',
      color: '#32CD32',
      index: 42,
    },
    {
      source: '4zwflvuesg',
      sourceAnchor: 3,
      target: 'admy50eir2r',
      targetAnchor: 3,
      id: '38a97e50',
      color: '#32CD32',
      index: 43,
    },
    {
      source: 'a0e02mt8bu',
      sourceAnchor: 2,
      target: '0wsqltn3b1dj',
      targetAnchor: 0,
      id: '755ee2c3',
      color: '#EC3D3D',
      index: 44,
    },
  ],
  groups: [
    {
      id: '4b87k8qkz58',
      label: '打开url',
      collapsed: false,
      FlowIndex: 2,
      isUsedCount: 2,
      useOtherCount: 0,
      x: 348.515625,
      y: -170,
      index: 1,
    },
    {
      id: '4c84k0uphrb',
      label: '重命名1',
      collapsed: false,
      FlowIndex: 4,
      isUsedCount: 0,
      useOtherCount: 3,
      x: 364.515625,
      y: 309,
      index: 2,
    },
    {
      id: 'h4o2czioea6',
      label: 'ViewPnt',
      collapsed: false,
      FlowIndex: 3,
      isUsedCount: 3,
      useOtherCount: 2,
      x: 354.515625,
      y: 70,
      index: 9,
    },
  ],
};

export default mockFlowData;
